# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ActiveRecord::Base.transaction do
  Stock.destroy_all

  stock = {
    '1' => {
      'name' => 'Amazon.com, Inc.',
      'symbol' => 'AMZN',
      'stock_desc' => 'Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally. The company operates through three segments: North America, International, and Amazon Web Services (AWS). It sells merchandise and content purchased for resale from third-party sellers through physical and online stores. The company also manufactures and sells electronic devices, including Kindle, Fire tablets, Fire TVs, Rings, and Echo and other devices; provides Kindle Direct Publishing, an online service that allows independent authors and publishers to make their books available in the Kindle Store; and develops and produces media content. In addition, it offers programs that enable sellers to sell their products on its Websites, as well as its stores; and programs that allow authors, musicians, filmmakers, skill and app developers, and others to publish and sell content. Further, the company provides compute, storage, database, and other AWS services, as well as fulfillment, advertising, publishing, and digital content subscriptions. Additionally, it offers Amazon Prime, a membership program, which provides free shipping of various items; access to streaming of movies and TV episodes; and other services. The company also operates in the food delivery business in Bengaluru, India. It serves consumers, sellers, developers, enterprises, and content creators. The company also has utility-scale solar projects in China, Australia, and the United States. Amazon.com, Inc. was founded in 1994 and is headquartered in Seattle, Washington.',
    },
    '2' => {
      'name' => 'Apple Inc.',
      'symbol' => 'AAPL',
      'stock_desc' => 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch, and other Apple-branded and third-party accessories. It also provides AppleCare support services; cloud services store services; and operates various platforms, including the App Store, that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It sells and delivers third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1977 and is headquartered in Cupertino, California.',
    },
    '3' => {
      'name' => 'Walmart Inc.',
      'symbol' => 'WMT',
      'stock_desc' => 'Walmart Inc. engages in the retail and wholesale operations in various formats worldwide. The company operates in three segments: Walmart U.S., Walmart International, and Sam\'s Club. It operates supercenters, supermarkets, hypermarkets, warehouse clubs, cash and carry stores, discount stores, drugstores, and convenience stores; membership-only warehouse clubs; ecommerce websites, such as walmart.com, walmart.com.mx, asda.com, walmart.ca, flipkart.com, and samsclub.com; and mobile commerce applications. The company offers grocery products, including meat, produce, natural and organics, deli and bakery, dairy, frozen foods, alcoholic and nonalcoholic beverages, and floral and dry grocery, as well as consumables, such as health and beauty aids, baby products, household chemicals, paper goods, and pet supplies; and health and wellness products. It also provides electronics, cameras and supplies, photo processing services, wireless, movies, music, video games, and books; stationery, automotive, hardware and paint, sporting goods, and outdoor living and horticulture; apparel for women, girls, men, boys, and infants, as well as shoes, jewelry, and accessories; and home furnishings, housewares and small appliances, bedding, home decor, toys, fabrics, crafts, and seasonal merchandise, as well as brand name merchandise. In addition, the company offers fuel and financial services and related products, including money orders, prepaid cards, money transfers, check cashing, and bill payment. It operates approximately 11,500 stores and various e-commerce Websites under the 56 banners in 27 countries. The company was formerly known as Wal-Mart Stores, Inc. and changed its name to Walmart Inc. in February 2018. Walmart Inc. was founded in 1945 and is based in Bentonville, Arkansas.',
    },
    '4' => {
      'name' => 'Berkshire Hathaway Inc.',
      'symbol' => 'BRK-B',
      'stock_desc' => 'Berkshire Hathaway Inc., through its subsidiaries, engages in insurance, freight rail transportation, and utility businesses. It provides property, casualty, life, accident, and health insurance and reinsurance; and operates railroad systems in North America. The company also generates, transmits, stores, and distributes electricity from natural gas, coal, wind, solar, hydro, nuclear, and geothermal sources; operates natural gas distribution and storage facilities, interstate pipelines, and compressor and meter stations; and holds interest in coal mining assets. In addition, it offers real estate brokerage services; and leases transportation equipment and furniture. Further, the company manufactures boxed chocolates and other confectionery products; specialty chemicals, metal cutting tools, and components for aerospace and power generation applications; flooring, insulation, roofing and engineered, building and engineered components, paints and coatings, and bricks and masonry products, as well as offers homebuilding and manufactured housing finance; and recreational vehicles, apparel products, jewelry, and custom picture framing products, and alkaline batteries. Additionally, it manufactures castings, forgings, fasteners/fastener systems, and aerostructures; and seamless pipes, fittings, downhole casing and tubing, and various mill forms. The company distributes newspapers, televisions, and information; franchises and services quick service restaurants; distributes electronic components; and offers logistics services, grocery and foodservice distribution services, and professional aviation training and fractional aircraft ownership programs. It also retails automobiles; furniture, bedding, and accessories; household appliances, electronics, and computers; jewelry, watches, crystal, china, stemware, flatware, gifts, and collectibles; kitchenware; and motorcycle accessories. The company was incorporated in 1998 and is headquartered in Omaha, Nebraska.',
    },
    '5' => {
      'name' => 'Facebook, Inc.',
      'symbol' => 'FB',
      'stock_desc' => 'Facebook, Inc. develops products that enable people to connect and share with friends and family through mobile devices, personal computers, virtual reality headsets, and in-home devices worldwide. The company\'s products include Facebook that enables people to connect, share, discover, and communicate with each other on mobile devices and personal computers; Instagram, a community for sharing photos, videos, and private messages; Messenger, a messaging application for people to connect with friends, family, groups, and businesses across platforms and devices; and WhatsApp, a messaging application that is used by people and businesses to communicate in a private way. It also provides Oculus, a hardware, software, and developer ecosystem, which allows people to come together and connect with each other through its Oculus virtual reality products. Facebook, Inc. was founded in 2004 and is headquartered in Menlo Park, California.',
    },
    '6' => {
      'name' => 'Tesla, Inc.',
      'symbol' => 'TSLA',
      'stock_desc' => 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, Netherlands, Norway, and internationally. The company operates in two segments, Automotive; and Energy Generation and Storage. The Automotive segment offers sedans and sport utility vehicles. It also provides electric powertrain components and systems; and services for electric vehicles through its company-owned service locations, and Tesla mobile service technicians, as well as sells used vehicles. This segment markets and sells its products through a network of company-owned stores and galleries, as well as through its own Website. The Energy Generation and Storage segment offers energy storage products, such as rechargeable lithium-ion battery systems for use in homes, industrial, commercial facilities, and utility grids; and designs, manufactures, installs, maintains, leases, and sells solar energy generation and energy storage products to residential and commercial customers. It also provides vehicle insurance services, as well as renewable energy. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was founded in 2003 and is headquartered in Palo Alto, California.',
    },
    '7' => {
      'name' => 'Snowflake Inc.',
      'symbol' => 'SNOW',
      'stock_desc' => 'Snowflake Inc. provides cloud-based data platform in the United States and internationally. The company\'s platform enables customers to consolidate data into a single source of truth to drive meaningful business insights, build data-driven applications, and share data. Its platform is used by various organizations of various sizes in a range of industries. The company was formerly known as Snowflake Computing, Inc. and changed its name to Snowflake Inc. in April 2019. Snowflake Inc. was founded in 2012 and is headquartered in San Mateo, California.',
    },
    '8' => {
      'name' => 'Barrick Gold',
      'symbol' => 'GOLD',
      'stock_desc' => 'Barrick Gold Corporation engages in the exploration, mine development, production, and sale of gold and copper properties. It has ownership interests in producing gold mines that are located in Argentina, Canada, CÃ´te d\'Ivoire, the Democratic Republic of Congo, the Dominican Republic, Mali, Papua New Guinea, Tanzania, and the United States. The company also has ownership interests in producing copper mines located in Chile, Saudi Arabia, and Zambia; and various other projects located throughout the Americas. Barrick Gold Corporation was founded in 1983 and is headquartered in Toronto, Canada.',
    },
    '9' => {
      'name' => 'Microsoft Corporation',
      'symbol' => 'MSFT',
      'stock_desc' => 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); Skype, Outlook.com, and OneDrive; LinkedIn that includes Talent, Learning, Sales, and Marketing solutions, as well as premium subscriptions; and Dynamics 365, a set of cloud-based and on-premises business solutions for small and medium businesses, large organizations, and divisions of enterprises. Its Intelligent Cloud segment licenses SQL and Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also offers support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification to developers and IT professionals on various Microsoft products. Its More Personal Computing segment provides Windows original equipment manufacturer (OEM) licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also offers Surface, PC accessories, PCs, tablets, gaming and entertainment consoles, and other intelligent devices; Gaming, including Xbox hardware, and Xbox content and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online stores, and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.',
    },
    '10' => {
      'name' => 'Caterpillar Inc.',
      'symbol' => 'CAT',
      'stock_desc' => 'Caterpillar Inc. manufactures and sells construction and mining equipment, diesel and natural gas engines, and industrial gas turbines. Its Construction Industries segment offers asphalt pavers, compactors, cold planers, feller bunchers, harvesters, motorgraders, pipelayers, road reclaimers, skidders, telehandlers, and utility vehicles; backhoe, knuckleboom, compact track, multi-terrain, skid steer, and track-type loaders; forestry and wheel excavators; and site prep and track-type tractors. The company\'s Resource Industries segment provides electric rope and hydraulic shovels, draglines, rotary drills, hard rock vehicles, track-type tractors, mining trucks, longwall miners, wheel loaders, off-highway and articulated trucks, wheel tractor scrapers, wheel dozers, landfill and soil compactors, machinery components, autonomous vehicles and solutions, select work tools, and hard rock continuous mining systems. Its Energy & Transportation segment offers reciprocating engine powered generator sets; reciprocating engines and integrated systems for the power generation, marine, oil, and gas industries; turbines, centrifugal gas compressors, and related services; remanufactured reciprocating engines and components; and diesel-electric locomotives and components, and other rail-related products. The company\'s Financial Products segment provides operating and finance leases, installment sale contracts, working capital loans, and wholesale financing; and insurance and risk management. Its All Other operating segment manufactures filters and fluids, undercarriage, ground engaging tools, fluid transfer products, precision seals, and rubber sealing and connecting components; parts distribution; integrated logistics solutions and distribution services; and digital investments services. The company was formerly known as Caterpillar Tractor Co. and changed its name to Caterpillar Inc. in 1986. The company was founded in 1925 and is headquartered in Deerfield, Illinois.',
    },
    '11' => {
      'name' => '3M Company',
      'symbol' => 'MMM',
      'stock_desc' => '3M Company develops, manufactures, and markets various products worldwide. It operates through four business segments: Safety and Industrial, Transportation and Electronics, Health Care, and Consumer. The Safety and Industrial segment offers personal safety products, industrial adhesives and tapes, abrasives, closure and masking systems, electrical markets, automotive aftermarket, and roofing granules to industrial, electrical, and safety markets. The Transportation and Electronics provides electronics, such as display materials and systems, electronic materials solutions; automotive and aerospace, and commercial solutions; advanced materials; and transportation safety products to transportation and electronic original equipment manufacturer customers. The Health Care segment offers medical and surgical supplies, skin health and infection prevention products, oral care, separation and purification sciences, health information systems, drug delivery systems, and food safety products to healthcare industry. The Consumer segment provides home improvement, home care, and consumer health care products, as well as stationery and office supplies to various consumers. This segment is also involved in the retail auto care business. It offers its products through various e-commerce and traditional wholesalers, retailers, jobbers, distributors, and dealers, as well as directly to users. 3M Company has a strategic collaboration with Merry Maids in residential cleaning sector. The company was founded in 1902 and is headquartered in St. Paul, Minnesota.',
    },
    '12' => {
      'name' => 'American Express Company',
      'symbol' => 'AXP',
      'stock_desc' => 'American Express Company, together with its subsidiaries, provides charge and credit payment card products, and travel-related services worldwide. The company operates through three segments: Global Consumer Services Group, Global Commercial Services, and Global Merchant and Network Services. Its products and services include payment and financing products; network services; expense management products and services; and lifestyle services. The company\'s products and services also comprise merchant acquisition and processing, servicing and settlement, point-of-sale marketing, and information products and services for merchants; and fraud prevention services, as well as the design and operation of customer loyalty programs. It sells its products and services to consumers, small businesses, mid-sized companies, and large corporations through mobile and online applications, third-party vendors and business partners, direct mail, telephone, in-house sales teams, and direct response advertising. American Express Company was founded in 1850 and is headquartered in New York, New York.',
    },
    '13' => {
      'name' => 'The Boeing Company',
      'symbol' => 'BA',
      'stock_desc' => 'The Boeing Company, together with its subsidiaries, designs, develops, manufactures, sales, services, and supports commercial jetliners, military aircraft, satellites, missile defense, human space flight and launch systems, and services worldwide. The company operates through four segments: Commercial Airplanes; Defense, Space & Security; Global Services; and Boeing Capital. The Commercial Airplanes segment develops, produces, and markets commercial jet aircraft and provides fleet support services principally to the commercial airline industry. The Defense, Space & Security segment engages in the research, development, production, and modification of manned and unmanned military aircraft and weapons systems for strike, surveillance, and mobility, including fighter and trainer aircraft; vertical lift comprising rotorcraft and tilt-rotor aircraft; commercial derivative aircraft, such as anti-submarine and tanker aircraft; strategic defense and intelligence systems consisting of strategic missile and defense systems, cyber and information solutions, and intelligence systems, as well as command, control, communications, computers, intelligence, surveillance, and reconnaissance products; satellite systems, including government and commercial satellites, and space exploration. The Global Services segment offers various products and services comprising supply chain and logistics management, engineering, maintenance and modifications, upgrades and conversions, spare parts, pilot and maintenance training systems and services, technical and maintenance documents, and data analytics and digital services to commercial and defense customers. The Boeing Capital segment offers financing services and manages financing exposure for a portfolio of equipment under operating and finance leases, notes and other receivables, assets held for sale or re-lease, and investments. The Boeing Company was founded in 1916 and is based in Chicago, Illinois.',
    },
    '14' => {
      'name' => 'Cisco Systems Inc.',
      'symbol' => 'CSCO',
      'stock_desc' => 'Cisco Systems, Inc. designs, manufactures, and sells Internet Protocol based networking and other products related to the communications and information technology industry in the Americas, Europe, the Middle East, Africa, the Asia Pacific, Japan, and China. It provides infrastructure platforms, including networking technologies of switching, routing, wireless, and data center products that are designed to work together to deliver networking capabilities, and transport and/or store data. The company also offers collaboration products comprising unified communications, Cisco TelePresence, and conferencing, as well as the Internet of Things and analytics software. In addition, it provides security products, such as network security, cloud and email security, identity and access management, advanced threat protection, and unified threat management products; and cloud and system management products. Further, the company offers a range of service and support options for its customers, including technical support and advanced services. It serves businesses of various sizes, public institutions, governments, and service providers. The company sells its products and services directly, as well as through systems integrators, service providers, other resellers, and distributors. Cisco Systems, Inc. has a strategic alliance with Internet2 to deliver next-generation capabilities and software solutions. Cisco Systems, Inc. was founded in 1984 and is headquartered in San Jose, California.',
    },
    '15' => {
      'name' => 'The Coca Cola Company',
      'symbol' => 'KO',
      'stock_desc' => 'The Coca-Cola Company, a beverage company, manufactures, markets, and sells various nonalcoholic beverages worldwide. The company provides sparkling soft drinks; water, enhanced water, and sports drinks; juice, dairy, and plantÂbased beverages; tea and coffee; and energy drinks. It also offers beverage concentrates and syrups, as well as fountain syrups to fountain retailers, such as restaurants and convenience stores. The company sells its products under the Coca-Cola, Diet Coke/Coca-Cola Light, Coca-Cola Zero Sugar, Fanta, Fresca, Schweppes, Sprite, Thums Up, Aquarius, Ciel, Dasani, glacÃ©au smartwater, glacÃ©au vitaminwater, Ice Dew, I LOHAS, Powerade, Topo Chico, AdeS, Del Valle, fairlife, innocent, Minute Maid, Minute Maid Pulpy, Simply, ZICO, Ayataka, Costa, dogadan, FUZE TEA, Georgia, Gold Peak, HONEST TEA, and Kochakaden brands. It operates through a network of company-owned or controlled bottling and distribution operators, as well as through independent bottling partners, distributors, wholesalers, and retailers. The company was founded in 1886 and is headquartered in Atlanta, Georgia.',
    },
    '16' => {
      'name' => 'The Goldman Sachs Group, Inc.',
      'symbol' => 'GS',
      'stock_desc' => 'The Goldman Sachs Group, Inc. operates as an investment banking, securities, and investment management company worldwide. It operates in four segments: Investment Banking, Global Markets, Asset Management, and Consumer & Wealth Management. The company\'s Investment Banking segment provides financial advisory services, including strategic advisory assignments related to mergers and acquisitions, divestitures, corporate defense activities, restructurings, and spin-offs; and middle-market lending, relationship lending, and acquisition financing, as well as transaction banking services. This segment also offers underwriting services, such as equity underwriting for common and preferred stock and convertible and exchangeable securities; and debt underwriting for various types of debt instruments, including investment-grade and high-yield debt, bank and bridge loans, and emerging- and growth-market debt. Its Global Markets segment is involved in client execution activities for cash and derivative instruments; credit products; mortgages; currencies; commodities; and equities; and provision of equity intermediation, and equity financing services, as well as offers clearing, settlement and custody services. The company\'s Asset Management segment manages assets across various asset classes, including equity, fixed income, hedge funds, credit funds, private equity, real estate, currencies, and commodities; and provides customized investment advisory solutions, and financing services, as well as invests in corporate, real estate, and infrastructure entities. Its Consumer & Wealth Management segment offers wealth advisory and banking services, including financial planning, investment management, and lending; private banking and lending services; unsecured loans; and saving and time deposits. The company serves corporations, financial institutions, governments, and individuals. The Goldman Sachs Group, Inc. was founded in 1869 and is headquartered in New York, New York.',
    },
    '17' => {
      'name' => 'Honeywell International Inc.',
      'symbol' => 'HON',
      'stock_desc' => 'Honeywell International Inc. operates as a diversified technology and manufacturing company worldwide. The Aerospace segment offers auxiliary power units, propulsion engines, integrated avionics, environmental control and electric power systems, engine controls, flight safety, communications, navigation hardware, data and software applications, radar and surveillance systems, aircraft lighting, advanced systems and instruments, satellite and space components, and aircraft wheels and brakes; spare parts; repair, overhaul, and maintenance services; thermal systems; and connected solutions and data services for the aftermarket, as well as wireless connectivity, and management and technical services. The company\'s Honeywell Building Technologies segment offers advanced software applications for building control and optimization; sensors, switches, control systems and instruments for energy management; access control; video surveillance; fire products; remote patient monitoring systems; e-cooling heat transfer agents; and installation, maintenance, and upgrades of systems. Its Performance Materials and Technologies segment offers automation control, instrumentation, and advanced software and related services; catalysts and adsorbents, equipment, and consulting; and materials used to manufacture end products, such as bullet-resistant armor, nylon, computer chips, and pharmaceutical packaging, as well as Honeywell forge connected solutions. The company\'s Safety and Productivity Solutions segment provides personal protection equipment, apparel, gear, and footwear; gas detection technology; and cloud-based notification and emergency messaging; and mobile devices and software; supply chain and warehouse automation equipment, and software and solutions; custom-engineered sensors, switches, and controls; and software-based data and asset management productivity solutions. Honeywell International Inc. was incorporated in 1985 and is headquartered in Charlotte, North Carolina.',
    },
    '18' => {
      'name' => 'Int. Business Machines Corp.',
      'symbol' => 'IBM',
      'stock_desc' => 'International Business Machines Corporation operates as an integrated solutions and services company worldwide. Its Cloud & Cognitive Software segment offers software for vertical and domain-specific solutions in health, financial services, and Internet of Things (IoT), weather, and security software and services application areas; and customer information control system and storage, and analytics and integration software solutions to support client mission critical on-premise workloads in banking, airline, and retail industries. It also offers middleware and data platform software, including Red Hat, which enables the operation of clients\' hybrid multi-cloud environments; and Cloud Paks, WebSphere distributed, and analytics platform software, such as DB2 distributed, information integration, and enterprise content management, as well as IoT, Blockchain and AI/Watson platforms. The company\'s Global Business Services segment offers business consulting services; system integration, application management, maintenance, and support services for packaged software; finance, procurement, talent and engagement, industry-specific business process outsourcing services; IT infrastructure and platform services. Its Global Technology Services segment provides project, managed, outsourcing, and cloud-delivered services for enterprise IT infrastructure environments; and IT infrastructure support services. It\'s Systems segment offers servers for businesses, cloud service providers, and scientific computing organizations; data storage products and solutions; and z/OS, an enterprise operating system, as well as Linux. Its Global Financing segment provides lease, installment payment, loan financing, short-term working capital financing, and remanufacturing and remarketing services. It was formerly known as Computing-Tabulating-Recording Co. and changed its name to International Business Machines Corporation in 1924. It was founded in 1911 and is headquartered in Armonk, New York.',
    },
    '19' => {
      'name' => 'Intel Corporation',
      'symbol' => 'INTC',
      'stock_desc' => 'Intel Corporation designs, manufactures, and sells essential technologies for the cloud, smart, and connected devices worldwide. The company operates through DCG, IOTG, Mobileye, NSG, PSG, CCG, and All Other segments. It offers platform products, such as central processing units and chipsets, and system-on-chip and multichip packages; and non-platform or adjacent products comprising accelerators, boards and systems, connectivity products, and memory and storage products. The company also provides Internet of things products, including high-performance compute solutions for targeted verticals and embedded applications; and computer vision and machine learning-based sensing, data analysis, localization, mapping, and driving policy technology. It serves original equipment manufacturers, original design manufacturers, and cloud service providers. The company has collaborations with UC San Francisco\'s Center for Digital Health Innovation, Fortanix, and Microsoft Azure to establish a computing platform with privacy-preserving analytics to accelerate the development and validation of clinical algorithms. Intel Corporation was founded in 1968 and is headquartered in Santa Clara, California.',
    },
    '20' => {
      'name' => 'The Walt Disney Company',
      'symbol' => 'DIS',
      'stock_desc' => 'The Walt Disney Company, together with its subsidiaries, operates as an entertainment company worldwide. The company\'s Media Networks segment operates domestic cable networks under the Disney, ESPN, Freeform, FX, and National Geographic brands; and television broadcast network under the ABC brand, as well as eight owned domestic television stations. This segment is also involved in the television production and distribution; and operation of National Geographic magazines. Its Parks, Experiences and Products segment operates theme parks and resorts, such as Walt Disney World Resort in Florida; Disneyland Resort in California; Disneyland Paris; Hong Kong Disneyland Resort; and Shanghai Disney Resort; Disney Cruise Line, Disney Vacation Club, National Geographic Expeditions, and Adventures by Disney; and Aulani, a Disney resort and spa in Hawaii, as well as licenses its intellectual property to a third party for the operations of the Tokyo Disney Resort in Japan. The company\'s Studio Entertainment segment produces and distributes motion pictures under the Walt Disney Pictures, Twentieth Century Fox, Marvel, Lucasfilm, Pixar, Fox Searchlight Pictures, and Blue Sky Studios banners; develops, produces, and licenses live entertainment events; produces and distributes music; and provides post-production services, including visual and audio effects. Its Direct-To-Consumer & International segment operates international television networks and channels comprising Disney, ESPN, Fox, National Geographic, Star, and Other India Channels; direct-to-consumer streaming services consisting of Disney +, ESPN+, Hotstar, and Hulu; and operates branded apps and Websites, such as Disney Movie Club and Disney Digital Network, as well as provides streaming technology support services. The company was founded in 1923 and is based in Burbank, California.',
    },
    '21' => {
      'name' => 'Visa Inc.',
      'symbol' => 'V',
      'stock_desc' => 'Visa Inc. operates as a payments technology company worldwide. The company facilitates commerce through the transfer of value and information among consumers, merchants, financial institutions, businesses, strategic partners, and government entities. It operates VisaNet, a processing network that enables authorization, clearing, and settlement of payment transactions. In addition, the company offers card products, as well as value-added services. It provides its services under the Visa, Visa Electron, Interlink, V PAY, and PLUS brands. Visa Inc. has a strategic partnership with NovoPayment to enable financial institutions and merchants to deploy Visa\'s digital solutions in Latin America and the Caribbean; and a strategic agreement with Intuit Inc. The company was founded in 1958 and is headquartered in San Francisco, California.',
    },
    '22' => {
      'name' => 'Verizon Communications Inc.',
      'symbol' => 'VZ',
      'stock_desc' => 'Verizon Communications Inc. offers communications, information, and entertainment products and services to consumers, businesses, and governmental entities worldwide. Its Consumer segment provides postpaid and prepaid service plans; Internet access on notebook computers and tablets; wireless equipment, including smartphones and other handsets; and wireless-enabled Internet devices, such as tablets, laptop computers and netbooks, and other wireless-enabled connected devices, such as smart watches and other wearables. It also provides residential fixed connectivity solutions, including Internet, video, and voice services; and sells network access to mobile virtual network operators. As of December 31, 2019, it had approximately 95 million wireless retail connections, 6 million broadband connections, and 4 million Fios video connections. The company\'s Business segment provides network connectivity products, including private networking, private cloud connectivity, virtual and software defined networking, and Internet access services; and Internet protocol-based voice services, unified communications and collaboration tools, and customer contact center solutions. It also offers a suite of management and data security services; domestic and global voice and data solutions, including voice calling, messaging services, conferencing, contact center solutions, and private line and data access networks; customer premises equipment; installation, maintenance, and site services; and IoT products and services. This segment had 25 million wireless retail postpaid connections and 489 thousand broadband connections. The company has strategic partnership with HERE Technologies and Dignitas; and Emory Healthcare to develop and test 5G Ultra Wideband-enabled use cases. The company was formerly known as Bell Atlantic Corporation and changed its name to Verizon Communications Inc. in June 2000. Verizon Communications Inc. was founded in 1983 and is headquartered in New York, New York.',
    },
    '23' => {
      'name' => 'JPMorgan Chase & Co.',
      'symbol' => 'JPM',
      'stock_desc' => 'JPMorgan Chase & Co. operates as a financial services company worldwide. It operates in four segments: Consumer & Community Banking (CCB), Corporate & Investment Bank (CIB), Commercial Banking (CB), and Asset & Wealth Management (AWM). The CCB segment offers deposit and investment products and services to consumers; lending, deposit, and cash management and payment solutions to small businesses; mortgage origination and servicing activities; residential mortgages and home equity loans; and credit card, payment processing, auto loan, and leasing services. The CIB segment provides investment banking products and services, including corporate strategy and structure advisory, and equity and debt markets capital-raising services, as well as loan origination and syndication; cash management and liquidity solutions; and cash securities and derivative instruments, risk management solutions, prime brokerage, and research. This segment also offers securities services, including custody, fund accounting and administration, and securities lending products for asset managers, insurance companies, and public and private investment funds. The CB segment provides financial solutions, including lending, treasury, investment banking, and asset management to small business, large and midsized corporations, local governments, and nonprofit clients; and commercial real estate banking services to investors, developers, and owners of multifamily, as well as to office, retail, industrial, and affordable housing properties. The AWM segment offers investment and wealth management services across equities, fixed income, alternatives, and money market fund asset classes; multi-asset investment management services; retirement products and services; and brokerage and banking services. The company also provides ATM, online and mobile, and telephone banking services. The company was founded in 1799 and is headquartered in New York, New York.',
    },
    '24' => {
      'name' => 'Johnson & Johnson',
      'symbol' => 'JNJ',
      'stock_desc' => 'Johnson & Johnson researches and develops, manufactures, and sells various products in the health care field worldwide. It operates in three segments: Consumer, Pharmaceutical, and Medical Devices. The Consumer segment offers baby care products under the JOHNSON\'S brand; oral care products under the LISTERINE brand; beauty products under the AVEENO, CLEAN & CLEAR, DR. CI:LABO NEUTROGENA, and OGX brands; over-the-counter medicines, including acetaminophen products under the TYLENOL brand; cold, flu, and allergy products under the SUDAFED brand; allergy products under the BENADRYL and ZYRTEC brands; ibuprofen products under the MOTRIN IB brand; and acid reflux products under the PEPCID brand. This segment also provides women\'s health products, such as sanitary pads and tampons under the STAYFREE, CAREFREE, and o.b. brands; wound care products comprising adhesive bandages under the BAND-AID brand; and first aid products under the NEOSPORIN brand. The Pharmaceutical segment offers products in various therapeutic areas, including immunology, infectious diseases, neuroscience, oncology, pulmonary hypertension, and cardiovascular and metabolic diseases. The Medical Devices segment provides orthopedic products; general surgery, biosurgical, endomechanical, and energy products; electrophysiology products to treat cardiovascular diseases; and vision care products, such as disposable contact lenses and ophthalmic products related to cataract and laser refractive surgery. The company markets its products to general public, and retail outlets and distributors, as well as distributes directly to wholesalers, hospitals, and health care professionals for prescription use. Johnson & Johnson was founded in 1886 and is based in New Brunswick, New Jersey.',
    },
    '25' => {
      'name' => 'NIKE, Inc.',
      'symbol' => 'NKE',
      'stock_desc' => 'NIKE, Inc., together with its subsidiaries, designs, develops, markets, and sells athletic footwear, apparel, equipment, and accessories worldwide. The company offers NIKE brand products in six categories, including running, NIKE basketball, the Jordan brand, football, training, and sportswear. It also markets products designed for kids, as well as for other athletic and recreational uses, such as American football, baseball, cricket, golf, lacrosse, skateboarding, tennis, volleyball, walking, wrestling, and other outdoor activities; and apparel with licensed college and professional team and league logos, as well as sells sports apparel. In addition, the company sells a line of performance equipment and accessories comprising bags, socks, sport balls, eyewear, timepieces, digital devices, bats, gloves, protective equipment, and other equipment for sports activities; and various plastic products to other manufacturers. Further, it provides athletic and casual footwear, apparel, and accessories under the Jumpman trademark; casual sneakers, apparel, and accessories under the Converse, Chuck Taylor, All Star, One Star, Star Chevron, and Jack Purcell trademarks; and action sports and youth lifestyle apparel and accessories under the Hurley trademark. Additionally, the company licenses agreements that permit unaffiliated parties to manufacture and sell apparel, digital devices, and applications and other equipment for sports activities under NIKE-owned trademarks. It sells its products to footwear stores; sporting goods stores; athletic specialty stores; department stores; skate, tennis, and golf shops; and other retail accounts through NIKE-owned retail stores, digital platforms, independent distributors, licensees, and sales representatives. The company was formerly known as Blue Ribbon Sports, Inc. and changed its name to NIKE, Inc. in 1971. NIKE, Inc. was founded in 1964 and is headquartered in Beaverton, Oregon.',
    },
    '26' => {
      'name' => 'The Procter & Gamble Company',
      'symbol' => 'PG',
      'stock_desc' => 'The Procter & Gamble Company provides branded consumer packaged goods to consumers in North and Latin America, Europe, the Asia Pacific, Greater China, India, the Middle East, and Africa. It operates in five segments: Beauty; Grooming; Health Care; Fabric & Home Care; and Baby, Feminine & Family Care. The Beauty segment offers conditioners, shampoos, styling aids, and treatments; and antiperspirants and deodorants, personal cleansing, and skin care products under the Head & Shoulders, Herbal Essences, Pantene, Rejoice, Olay, Old Spice, Safeguard, SK-II, and Secret brands. The Grooming segment provides female and male blades and razors, pre- and post-shave products, and other shave care products; and appliances that include electric shavers and epilators under the Braun, Gillette, and Venus brands. The Health Care segment offers toothbrushes, toothpaste, and other oral care products; and gastrointestinal, rapid diagnostics, respiratory, vitamins/minerals/supplements, pain relief, and other personal health care products under the Crest, Oral-B, Metamucil, Neurobion, Pepto Bismol, and Vicks brands. The Fabric & Home Care segment provides fabric enhancers, laundry additives, and laundry detergents; and air care, dish care, P&G professional, and surface care products under the Ariel, Downy, Gain, Tide, Cascade, Dawn, Fairy, Febreze, Mr. Clean, and Swiffer brands. The Baby, Feminine & Family Care segment baby wipes, taped diapers, and pants; adult incontinence and feminine care products; and paper towels, tissues, and toilet papers under the Luvs, Pampers Always, Always Discreet, Tampax Bounty, Charmin, and Puffs brands. The company sells its products through mass merchandisers, e-commerce, grocery stores, membership club stores, drug stores, department stores, distributors, wholesalers, baby stores, specialty beauty stores, high-frequency stores, pharmacies, electronics stores, and professional channels. The Procter & Gamble Company was founded in 1837 and is headquartered in Cincinnati, Ohio.',
    },
    '27' => {
      'name' => 'Alphabet Inc.',
      'symbol' => 'GOOG',
      'stock_desc' => 'Alphabet Inc. provides online advertising services in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It offers performance and brand advertising services. The company operates through Google and Other Bets segments. The Google segment offers products, such as Ads, Android, Chrome, Google Cloud, Google Maps, Google Play, Hardware, Search, and YouTube, as well as technical infrastructure. It also offers digital content, cloud services, hardware devices, and other miscellaneous products and services. The Other Bets segment includes businesses, including Access, Calico, CapitalG, GV, Verily, Waymo, and X, as well as Internet and television services. The company has an agreement with Sabre Corporation to develop an artificial intelligence-driven technology platform for travel. Alphabet Inc. was founded in 1998 and is headquartered in Mountain View, California.',
    },
    '28' => {
      'name' => 'salesforce.com, Inc.',
      'symbol' => 'CRM',
      'stock_desc' => 'salesforce.com, inc. develops enterprise cloud computing solutions with a focus on customer relationship management worldwide. The company offers Sales Cloud to store data, monitor leads and progress, forecast opportunities, and gain insights through analytics and relationship intelligence, as well as deliver quotes, contracts, and invoices. It also provides Service Cloud, which enables companies to deliver personalized customer service and support, as well as a field service solution that enables companies to connect agents, dispatchers, and mobile employees through a centralized platform, which helps to schedule and dispatch work, and track and manage jobs in real-time. In addition, the company offers Marketing Cloud to plan, personalize, and optimize one-to-one customer marketing interactions; and Commerce Cloud, which enables companies to enhance engagement, conversion, revenue, and loyalty from their customers. Further, it provides Customer 360 Platform that offers no-code to pro-code Platform-as-a-Service tools for building, securing, integrating, and managing the business apps; MuleSoft Anypoint Platform enables customers to connect any system, application, data, or device; Quip collaboration platform, which combines documents, spreadsheets, apps, and chat with live CRM data; and Tableau and Einstein Analytics, provides analytical technology to customers. Additionally, the company offers various solutions for financial services, healthcare and life sciences, manufacturing, consumer goods, government, and philanthropy. The company also provides professional services and education services, including instructor-led and online courses; and support and adoption programs. It provides its services through direct sales; and consulting firms, systems integrators, and other partners. Salesforce and Siemens has a strategic partnership. The company was founded in 1999 and is headquartered in San Francisco, California.',
    },
    '29' => {
      'name' => 'Chevron Corporation',
      'symbol' => 'CVX',
      'stock_desc' => 'Chevron Corporation, through its subsidiaries, engages in integrated energy, chemicals, and petroleum operations worldwide. The company operates in two segments, Upstream and Downstream. The Upstream segment is involved in the exploration, development, and production of crude oil and natural gas; processing, liquefaction, transportation, and regasification associated with liquefied natural gas; transportation of crude oil through pipelines; and transportation, storage, and marketing of natural gas, as well as operates a gas-to-liquids plant. The Downstream segment engages in refining crude oil into petroleum products; marketing crude oil and refined products; transporting crude oil and refined products through pipeline, marine vessel, motor equipment, and rail car; and manufacturing and marketing commodity petrochemicals, and fuel and lubricant additives, as well as plastics for industrial uses. Chevron Corporation is also involved in the cash management and debt financing activities; insurance operations; real estate activities; and technology businesses. The company was formerly known as ChevronTexaco Corporation and changed its name to Chevron Corporation in 2005. Chevron Corporation was founded in 1879 and is headquartered in San Ramon, California.',
    },
    '30' => {
      'name' => 'Accenture plc',
      'symbol' => 'ACN',
      'stock_desc' => 'Accenture plc, a professional services company, provides strategy and consulting, interactive, and technology and operations services worldwide. The company also provides outsourcing services. It serves communications, media, high tech, software, and platform companies; banking, capital market, and insurance industries; and consumer goods, retail, travel services, industrial, and life science industries, as well as clients in health, public service, chemicals and natural resources, energy, and utilities sectors. Accenture plc has alliance relationships with Adobe, Alibaba, Amazon Web Services, Blue Yonder, Cisco, Dell, Google, HPE, IBM RedHat, Microsoft, Oracle, Pegasystems, Salesforce, SAP, ServiceNow, VMWare, Workday, and Massachusetts Institute of Technology. The company was incorporated in 2009 and is based in Dublin, Ireland.',
    },
    '31' => {
      'name' => 'Activision Blizzard, Inc.',
      'symbol' => 'ATVI',
      'stock_desc' => 'Activision Blizzard, Inc., together with its subsidiaries, develops and distributes content and services on video game consoles, personal computers (PC), and mobile devices in the Americas, Europe, the Middle East, Africa, and the Asia Pacific. The company operates through three segments: Activision Publishing, Inc.; Blizzard Entertainment, Inc.; and King Digital Entertainment. It develops, publishes, and sells interactive software products and entertainment content for the console and PC platforms through retail and digital channels, including subscription, full-game, and in-game sales, as well as by licensing software to third-party or related-party companies; and offer downloadable content. The company also maintains a proprietary online gaming service, Battle.net that facilitates the creation of user generated content, digital distribution, and online social connectivity in its games; and develops and publishes interactive entertainment content and services primarily on mobile platforms, such as Android and iOS, as well as distributes its content and services on the PC platform primarily through Facebook. In addition, it operate esports leagues and offer digital advertising content; and provides warehousing, logistics, and sales distribution services to third-party publishers of interactive entertainment software, as well as manufacturers of interactive entertainment hardware products. The company\'s key product franchises include Call of Duty, World of Warcraft, Diablo, Hearthstone, Overwatch, and Candy Crush. It serves retailers and distributors, including mass-market retailers, first party digital storefronts, consumer electronics stores, discount warehouses, and game specialty stores through third-party distribution and licensing arrangements. Activision Blizzard, Inc. was incorporated in 1979 and is headquartered in Santa Monica, California.',
    },
    '32' => {
      'name' => 'Adobe Systems Incorporated',
      'symbol' => 'ADBE',
      'stock_desc' => 'Adobe Inc. operates as a diversified software company worldwide. Its Digital Media segment provides tools and solutions that enable individuals, teams, and enterprises to create, publish, promote, and monetize their digital content. Its flagship product is Creative Cloud, a subscription service that allows customer to download and access the latest versions of its creative products. This segment serves content creators, experience designers, app developers, enthusiasts, students, social media users, and creative professionals, as well as marketing departments and agencies, companies and publishers. The company\'s Digital Experience segment offers products, services, and solutions for creating, managing, executing, measuring, monetizing and optimizing customer experiences from advertising to commerce. This segment serves marketers, advertisers, agencies, publishers, merchandisers, merchants, web analysts, data scientists, developers, marketing executives, information management and technology executives, product development executives, and sales and support executives. Its Publishing segment offers products and services, such as e-learning solutions, technical document publishing, web conferencing, document and forms platform, web application development, and high-end printing, as well as publishing needs of technical and business, and original equipment manufacturers (OEMs) printing businesses. The company offers its products and services directly to enterprise customers through its sales force and local field offices, as well as to end-users through app stores and through its Website at adobe.com. It also distributes products and services through a network of distributors, value-added resellers, systems integrators, software vendors and developers, retailers, and OEMs. The company was formerly known as Adobe Systems Incorporated and changed its name to Adobe Inc. in October 2018. The company was founded in 1982 and is headquartered in San Jose, California.',
    },
    '33' => {
      'name' => 'Kellog',
      'symbol' => 'K',
      'stock_desc' => 'Kellogg Company, together with its subsidiaries, manufactures and markets ready-to-eat cereal and convenience foods. The company operates through four segments: North America, Europe, Latin America, and Asia Middle East Africa. Its principal products include crackers, crisps, savory snacks, toaster pastries, cereal bars, granola bars and bites, ready-to-eat cereals, frozen waffles, veggie foods, and noodles. The company offers its products under the Kellogg\'s, Cheez-It, Pringles, Austin, Parati, RXBAR, Kashi, Bear Naked, Eggo, Morningstar Farms, Choco Krispies, Crunchy Nut, Nutri-Grain, Special K, Squares, Zucaritas, Sucrilhos, Pop-Tarts, K-Time, Split Stix, Be Natural, LCMs, Coco Pops, Rice Krispies Squares, Kashi Go, Vector, and Gardenburger brand names. It sells its products to retailers through direct sales forces, as well as brokers and distributors. Kellogg Company was founded in 1906 and is headquartered in Battle Creek, Michigan.',
    },
    '34' => {
      'name' => 'Lockheed Martin Corporation',
      'symbol' => 'LMT',
      'stock_desc' => 'Lockheed Martin Corporation, a security and aerospace company, engages in the research, design, development, manufacture, integration, and sustainment of technology systems, products, and services worldwide. It operates through four segments: Aeronautics, Missiles and Fire Control, Rotary and Mission Systems, and Space Systems. The Aeronautics segment offers combat and air mobility aircraft, unmanned air vehicles, and related technologies. The Missiles and Fire Control segment provides air and missile defense systems; tactical missiles and air-to-ground precision strike weapon systems; logistics; fire control systems; mission operations support, readiness, engineering support, and integration services; manned and unmanned ground vehicles; and energy management solutions. The Rotary and Mission Systems segment offers military and commercial helicopters; ship and submarine mission and combat systems; mission systems and sensors for rotary and fixed-wing aircraft; sea and land-based missile defense systems; radar systems; the Littoral combat ship; simulation and training services; and unmanned systems and technologies. It also supports government customers in cybersecurity; and delivers communications, and command and control capabilities through mission solutions for defense applications. The Space Systems segment offers satellites; space transportation systems; strategic, advanced strike, and defensive missile systems; and classified systems and services in support of national security systems. This segment also provides network-enabled situational awareness and integrates space and ground-based systems to help its customers gather, analyze, and securely distribute critical intelligence data. Lockheed Martin Corporation was founded in 1912 and is headquartered in Bethesda, Maryland.',
    },
    '35' => {
      'name' => 'American Airlines Group Inc.',
      'symbol' => 'AAL',
      'stock_desc' => 'American Airlines Group Inc., through its subsidiaries, operates as a network air carrier. It provides scheduled air transportation services for passengers and cargo. As of December 31, 2019, the company operated a mainline fleet of 942 aircraft. It serves 365 destinations in approximately 61 countries, principally from its hubs and gateways in Charlotte, Chicago, Dallas/Fort Worth, London Heathrow, Los Angeles, Miami, New York, Philadelphia, Phoenix, and Washington, D.C. American Airlines Group Inc. has strategic partnership with JetBlue Airways Corp. The company was formerly known as AMR Corporation and changed its name to American Airlines Group Inc. in December 2013. American Airlines Group Inc. was founded in 1930 and is headquartered in Fort Worth, Texas.',
    },
    '36' => {
      'name' => 'Under Armour, Inc.',
      'symbol' => 'UA',
      'stock_desc' => 'Under Armour, Inc., together with its subsidiaries, develops, markets, and distributes branded performance apparel, footwear, and accessories for men, women, and youth primarily in North America, Europe, the Middle East, Africa, the Asia-Pacific, and Latin America. The company offers its apparel in compression, fitted, and loose types to be worn in hot and cold. It also provides various footwear products for running, basketball, cleated sports, training, and outdoor. In addition, the company offers accessories, which include gloves, bags, and headwear; and digital fitness subscriptions, as well as digital advertising through MapMyFitness, MyFitnessPal, and Endomondo platforms. It primarily offers its products under the HEATGEAR, COLDGEAR, RUSH or RECOVER, UA Logo, UNDER ARMOUR, UA, ARMOUR, PROTECT THIS HOUSE, I WILL, ARMOURBOX, ARMOUR BRA, and ARMOUR FLEECE, as well as MyFitnessPal, MapMyFitness, and UNDER ARMOUR CONNECTED FITNESS brands. The company sells its products through wholesale channels, including national and regional sporting goods chains, independent and specialty retailers, department store chains, institutional athletic departments, and leagues and teams, as well as independent distributors; and directly to consumers through a network of 388 brand and factory house stores, as well as through e-commerce websites. Under Armour, Inc. was founded in 1996 and is headquartered in Baltimore, Maryland.',
    },
    '37' => {
      'name' => 'Waste Management, Inc.',
      'symbol' => 'WM',
      'stock_desc' => 'Waste Management, Inc., through its subsidiaries, provides waste management environmental services to residential, commercial, industrial, and municipal customers in North America. It offers collection services, including picking up and transporting waste and recyclable materials from where it was generated to a transfer station, material recovery facility (MRF), or disposal site; and owns, develops, and operates landfill gas-to-energy facilities in the United States, as well as owns and operates transfer stations. As of December 31, 2019, the company owned or operated 244 solid waste landfills; 5 secure hazardous waste landfills; 103 MRFs; and 302 transfer stations. It also provides materials processing and commodities recycling services; recycling brokerage services, such as managing the marketing of recyclable materials for third parties; and other strategic business solutions. In addition, the company offers construction and remediation services; services related with the disposal of fly ash, and residue generated from the combustion of coal and other fuel stocks; in-plant services comprising full-service waste management solutions and consulting services; and specialized disposal services for oil and gas exploration and production operations. Further, it offers fluorescent bulb and universal waste mail-back services through LampTracker program; portable restroom services under the Port-o-Let name; and street and parking lot sweeping services, as well as holds interests in oil and gas producing properties. The company was formerly known as USA Waste Services, Inc. and changed its name to Waste Management, Inc. in 1998. Waste Management, Inc. was incorporated in 1987 and is based in Houston, Texas.',
    },
    '38' => {
      'name' => 'Wells Fargo & Company',
      'symbol' => 'WFC',
      'stock_desc' => 'Wells Fargo & Company, a diversified financial services company, provides banking, investment, mortgage, and consumer and commercial finance products and services to individuals, businesses, and institutions in the United States and internationally. It operates in three segments: Community Banking, Wholesale Banking, and Wealth and Investment Management. The Community Banking segment offers checking and savings accounts; credit and debit cards; and automobile, student, mortgage, home equity, and small business lending products. The Wholesale Banking segment provides commercial, corporate, capital markets, cash management, and real estate banking products and services, including traditional commercial loans and lines of credit, letters of credit, asset-based lending, equipment leasing, international trade facilities, trade financing, collection services, foreign exchange services, treasury management, institutional fixed-income sales, interest rate, commodity and equity risk management, online/electronic products, corporate trust fiduciary and agency services, and investment banking services. It also offers commercial and residential development, land acquisition and development, rehabilitation, permanent securitization, and commercial real estate loans; secured and unsecured lines of credit; affordable housing loans and letters of credit; and interim financing arrangements. The Wealth and Investment Management segment provides personalized wealth management, investment, and retirement products and services; and delivers financial planning, private banking, credit, investment management, and fiduciary services. The company also offers brokerage, and Internet and mobile banking services; and has collaboration with National LGBT Chamber of Commerce. As of March 16, 2020, it operated through 7,400 locations; approximately 13,000 ATMs; and offices in 32 countries and territories. The Company was founded in 1852 and is headquartered in San Francisco, California.',
    },
    '39' => {
      'name' => 'Comcast Corporation',
      'symbol' => 'CMCSA',
      'stock_desc' => 'Comcast Corporation operates as a media and technology company worldwide. It operates through Cable Communications, Cable Networks, Broadcast Television, Filmed Entertainment, Theme Parks, and Sky segments. The Cable Communications segment offers cable services, including high-speed Internet, video, voice, wireless, and security and automation services to residential and business customers under the Xfinity brand; and advertising services. The Cable Networks segment operates national cable networks that provide various entertainment, news and information, and sports content; regional sports and news networks; international cable networks; and various digital properties, including brand-aligned Websites, as well as engages in the cable television studio production operations. The Broadcast Television segment operates NBC and Telemundo broadcast networks, NBC and Telemundo local broadcast television stations, broadcast television studio production operations, and various digital properties. The Filmed Entertainment segment produces, acquires, markets, and distributes filmed entertainment under the Universal Pictures, Illumination, DreamWorks Animation, and Focus Features names. It also develops, produces, and licenses stage plays; and distributes filmed entertainment produced by third parties. The Theme Parks segment operates Universal theme parks in Orlando, Florida; Hollywood, California; and Osaka, Japan. The Sky segment offers direct-to-consumer services, such as video, high-speed Internet, voice, and wireless phone services; and content services comprising operating entertainment networks, the Sky News broadcast network, and Sky Sports networks. The company also owns the Philadelphia Flyers, as well as the Wells Fargo Center arena in Philadelphia, Pennsylvania. Comcast Corporation was founded in 1963 and is headquartered in Philadelphia, Pennsylvania.',
    },
    '40' => {
      'name' => 'eBay Inc.',
      'symbol' => 'EBAY',
      'stock_desc' => 'eBay Inc. operates the marketplace and classifieds platforms that connect buyers and sellers worldwide. Its Marketplace platform includes its online marketplace at ebay.com and the eBay suite of mobile apps; and Classifieds platform comprises a collection of brands, such as Mobile.de, Kijiji, Gumtree, Marktplaats, eBay Kleinanzeigen, and others that offer online classifieds to help people find what they are looking for in their local communities. Its platforms enable users to list, buy, sell, and pay for items through various online, mobile, and offline channels that include retailers, distributors, liquidators, import and export companies, auctioneers, catalog and mail-order companies, classifieds, directories, search engines, commerce participants, shopping channels, and networks. The company was founded in 1995 and is headquartered in San Jose, California.',
    },
    '41' => {
      'name' => 'Electronic Arts',
      'symbol' => 'EA',
      'stock_desc' => 'Electronic Arts Inc. develops, markets, publishes, and distributes games, content, and services for game consoles, PCs, mobile phones, and tablets worldwide. The company develops and publishes games and services across various genres, such as sports, first-person shooter, action, role-playing, and simulation primarily under the Battlefield, The Sims, Apex Legends, Need for Speed, and Plants v. Zombies brands; and license games from others, including FIFA, Madden NFL, and Star Wars brands. It also provides advertising services; and licenses its games to third parties to distribute and host its games. The company markets and sells its games and services through digital distribution and retail channels, as well as directly to mass market retailers, specialty stores, and distribution arrangements. It has a strategic partnership with KLab Inc. for game development and operation. Electronic Arts Inc. was founded in 1982 and is headquartered in Redwood City, California.',
    },
    '42' => {
      'name' => 'Expedia Group, Inc.',
      'symbol' => 'EXPE',
      'stock_desc' => 'Expedia Group, Inc. operates as an online travel company worldwide. It operates through four segments: Core Online Travel Agencies, Trivago, Vrbo, and Egencia. Its brand portfolio include Brand Expedia, a full-service online travel brand with localized websites; Hotels.com for marketing and distributing lodging accommodations; Vrbo, an online marketplace for the alternative accommodations; Expedia Partner Solutions, a business-to-business brand that provides travel offerings for various airlines and hotels, online and offline travel agencies, loyalty and corporate travel companies, and various consumer brands; and Egencia, which provides corporate travel management services. The company\'s brand portfolio also comprise Orbitz, Travelocity, and CheapTickets travel Websites; ebookers, a full-service travel brand; Hotwire, an online travel Website; Expedia Group Media Solutions that provides media partnerships and digital marketing solutions; trivago, an online hotel metasearch platform; and Expedia Local Expert, a provider of online and in-market concierge services, activities, experiences, and ground transportation. In addition, its brand portfolio consists of CarRentals.com, an online car rental booking service; Classic Vacations, a luxury travel specialist; Expedia CruiseShipCenters, a provider of advice for travelers booking cruises and vacations; and SilverRail, a provider of a rail retail and distribution platform connecting rail carriers and suppliers to online and offline travel distributors. Further, the company provides online travel services through its Wotif.com, lastminute.com.au, travel.com.au, Wotif.co.nz, and lastminute.co.nz brands; loyalty programs; and advertising and media services. It serves leisure and corporate travelers. The company was formerly known as Expedia, Inc. and changed its name to Expedia Group, Inc. in March 2018. Expedia Group, Inc. was founded in 1996 and is headquartered in Seattle, Washington.',
    },
    '43' => {
      'name' => 'Exxon Mobil Corporation',
      'symbol' => 'XOM',
      'stock_desc' => 'Exxon Mobil Corporation explores for and produces crude oil and natural gas in the United States, Canada/other Americas, Europe, Africa, Asia, and Australia/Oceania. It operates through Upstream, Downstream, and Chemical segments. The company is also involved in the manufacture, trade, transport, and sale of crude oil, petroleum products, and other specialty products; and manufactures and markets petrochemicals, including olefins, polyolefins, aromatics, and various other petrochemicals. As of December 31, 2019, it had approximately 23,857 net operated wells with proved reserves of 22.4 billion oil-equivalent barrels. In addition, the company produces raw materials, such as polypropylene and isopropyl alcohol for medical masks, gowns, and hand sanitizer. The company was founded in 1870 and is based in Irving, Texas.',
    },
    '44' => {
      'name' => 'Starbucks Corporation',
      'symbol' => 'SBUX',
      'stock_desc' => 'Starbucks Corporation, together with its subsidiaries, operates as a roaster, marketer, and retailer of specialty coffee worldwide. The company operates through three segments: Americas, International, and Channel Development. Its stores offer coffee and tea beverages, roasted whole bean and ground coffees, single-serve and ready-to-drink beverages, and iced tea; and various food products, such as pastries, breakfast sandwiches, and lunch items. The company also licenses its trademarks through licensed stores, and grocery and foodservice accounts. The company offers its products under the Starbucks, Teavana, Seattle\'s Best Coffee, Evolution Fresh, Ethos, Starbucks Reserve, and Princi brand names. As of October 29, 2020, it operated approximately 32,000 stores. Starbucks Corporation was founded in 1971 and is based in Seattle, Washington.',
    },
    '45' => {
      'name' => 'The Kraft Heinz Company',
      'symbol' => 'KHC',
      'stock_desc' => 'The Kraft Heinz Company, together with its subsidiaries, manufactures and markets food and beverage products in the United States, Canada, the United Kingdom, and internationally. Its products include condiments and sauces, cheese and dairy, meals, meats and seafood, frozen and chilled foods, packaged drinking pouches, appetizers, refreshment beverages, coffee, nuts and salted snacks, infant and nutrition products, and other grocery products, as well as desserts, dressings, toppings, and baking. The company offers its products under the Kraft, Oscar Mayer, Heinz, Philadelphia, Lunchables, Velveeta, Planters, Maxwell House, Capri Sun, Ore-Ida, Kool-Aid, Jell-O, Classico, McCafe, Tassimo, TGI Fridays, Taco Bell Home Originals, Plasmon, Pudliszki, Honig, HP, Benedicta, Karvan Cevitam, ABC, Master, Quero, Golden Circle, and Wattie\'s names. It sells its products through its own sales organizations, as well as through independent brokers, agents, and distributors to chain, wholesale, cooperative and independent grocery accounts, convenience stores, drug stores, value stores, bakeries, pharmacies, mass merchants, club stores, foodservice distributors and institutions, including hotels, restaurants, hospitals, health care facilities, and government agencies; and online through e-commerce platforms and retailers. The company was formerly known as H.J. Heinz Holding Corporation and changed its name to The Kraft Heinz Company in July 2015. The Kraft Heinz Company was founded in 1869 and is headquartered in Pittsburgh, Pennsylvania.',
    },
    '46' => {
      'name' => 'Tiffany & Co.',
      'symbol' => 'TIF',
      'stock_desc' => 'Tiffany & Co., through its subsidiaries, designs, manufactures, and retails jewelry and other items. The company offers jewelry collections, engagement rings, and wedding bands. It also sells watches, home and accessories products, and fragrances; and wholesales diamonds and earnings. The company sells its products through retail, Internet and catalog, business-to-business, and wholesale distribution channels. As of January 31, 2020, it operated 124 stores in the Americas, 91 stores in the Asia-Pacific, 58 stores in Japan, 48 stores in Europe, and 5 stores in the United Arab Emirates. Tiffany & Co. was founded in 1837 and is headquartered in New York, New York.',
    },
    '47' => {
      'name' => 'Twitter, Inc.',
      'symbol' => 'TWTR',
      'stock_desc' => 'Twitter, Inc. operates as a platform for public self-expression and conversation in real time United States and internationally. The company offers various products and services, including Twitter, a platform that allows users to consume, create, distribute, and discover content; and Periscope, a mobile application that enables user to broadcast and watch video live with others. It also provides promoted products and services, such as promoted tweets, promoted accounts, and promoted trends, which enable its advertisers to promote their brands, products, and services. In addition, the company offers a set of tools and public application programming interfaces for developers to contribute their content to its platform, syndicate and distribute Twitter content across their properties, and enhance their Websites and applications with Twitter content. Further, it provides subscription access to its public data feed for data partners. Twitter, Inc. was founded in 2006 and is headquartered in San Francisco, California.',
    },
    '48' => {
      'name' => 'Oracle Corporation',
      'symbol' => 'ORCL',
      'stock_desc' => 'Oracle Corporation provides products and services that address enterprise information technology environments worldwide. The company\'s cloud and license business engages in the sale, marketing, and delivery of its applications and infrastructure technologies through cloud and on-premise deployment models, including cloud services and license support; and cloud license and on-premise license. Its cloud software as a service offerings include a suite of cloud software applications, including enterprise resource planning (ERP), enterprise and performance management, supply chain management, human capital management, and customer experience cloud-based industry solutions, as well as NetSuite application suite, a cloud-based ERP solution. The company also provides cloud infrastructure as a service; enterprise database; database products, including MySQL, Oracle TimesTen In-Memory Database, Oracle Berkeley DB, and Oracle NoSQL Database; middleware software; Java licenses; server and storage products; hardware products and services comprising point-of-sale terminals and related hardware for managing businesses within the food and beverage, hotel and retail industries; and hardware products and services for communications networks, including network signaling, policy control and subscriber data management solutions, and session border control technology. In addition, it offers operating systems, including Oracle Linux and Oracle Solaris, virtualization software, and other hardware-related software; management technologies and products, such as Oracle Enterprise Manager; and product repairs, maintenance services, and technical support services. It also serves various industries, government agencies, and educational institutions. The company was founded in 1977 and is headquartered in Redwood City, California.',
    },
    '49' => {
      'name' => 'PayPal Holdings, Inc.',
      'symbol' => 'PYPL',
      'stock_desc' => 'PayPal Holdings, Inc. operates as a technology platform and digital payments company that enables digital and mobile payments on behalf of consumers and merchants worldwide. Its payment solutions include PayPal, PayPal Credit, Braintree, Venmo, Xoom, and iZettle products. The company\'s payments platform allows consumers to send and receive payments, withdraw funds to their bank accounts, and hold balances in their PayPal accounts in various currencies. It also offers gateway services that enable merchants to accept payments online with credit or debit cards, as well as digital wallets. PayPal Holdings, Inc. was founded in 1998 and is headquartered in San Jose, California.',
    },
    '50' => {
      'name' => 'PepsiCo, Inc.',
      'symbol' => 'PEP',
      'stock_desc' => 'PepsiCo, Inc. operates as a food and beverage company worldwide. The company operates through seven segments: FLNA, QFNA, PBNA, LatAm, Europe, AMESA, and APAC. It offers branded dips, cheese-flavored snacks, and tortillas, as well as corn, potato, and tortilla chips; cereals, rice, pasta, mixes and syrups, granola bars, grits, oat squares, oatmeal, rice cakes, simply granola, and side dishes; beverage concentrates, fountain syrups, and finished goods; ready-to-drink tea, coffee, and juices; and dairy products. The company provides its products primarily under the Cheetos, Doritos, Fritos, Lay\'s, Ruffles, Tostitos, Aunt Jemima, Cap\'n crunch, Life, Pasta Roni, Quaker Chewy, Quaker, Rice-A-Roni, Aquafina, Diet Mountain Dew, Diet Pepsi, Gatorade, Mountain Dew, Pepsi, Propel, Sierra Mist, Tropicana, Emperador, Marias Gamesa, Rosquinhas Mabel, Sabritas, Saladitas, 7UP, Gatorade, H2oh!, Manzanita Sol, Mirinda, Pepsi, Pepsi Black, San Carlos, Toddy, Agusha, Chudo, and Domik v Derevne brands. It serves wholesale and other distributors, foodservice customers, grocery stores, drug stores, convenience stores, discount/dollar stores, mass merchandisers, membership stores, hard discounters, e-commerce retailers and authorized independent bottlers, and others through a network of direct-store-delivery, customer warehouse, and distributor networks, as well as directly to consumers through e-commerce platforms and retailers. The company was founded in 1898 and is headquartered in Purchase, New York.',
    },

  }

  stock = stock.map do |num, info|
    info['image_url'] = "assets/logos/#{num}.svg"
    info
  end

  Stock.create!(stock)
  
end
