# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ActiveRecord::Base.transaction do
  Stock.destroy_all

  stock = {
    '1' => {
      'name' => 'Amazon.com, Inc.',
      'symbol' => 'AMZN',
      'stock_desc' => 'Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally. The company operates through three segments: North America, International, and Amazon Web Services (AWS). It sells merchandise and content purchased for resale from third-party sellers through physical and online stores. The company also manufactures and sells electronic devices, including Kindle, Fire tablets, Fire TVs, Rings, and Echo and other devices; provides Kindle Direct Publishing, an online service that allows independent authors and publishers to make their books available in the Kindle Store; and develops and produces media content. In addition, it offers programs that enable sellers to sell their products on its Websites, as well as its stores; and programs that allow authors, musicians, filmmakers, skill and app developers, and others to publish and sell content. Further, the company provides compute, storage, database, and other AWS services, as well as fulfillment, advertising, publishing, and digital content subscriptions. Additionally, it offers Amazon Prime, a membership program, which provides free shipping of various items; access to streaming of movies and TV episodes; and other services. The company also operates in the food delivery business in Bengaluru, India. It serves consumers, sellers, developers, enterprises, and content creators. The company also has utility-scale solar projects in China, Australia, and the United States. Amazon.com, Inc. was founded in 1994 and is headquartered in Seattle, Washington.',
    },
    '2' => {
      'name' => 'Apple Inc.',
      'symbol' => 'AAPL',
      'stock_desc' => 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch, and other Apple-branded and third-party accessories. It also provides AppleCare support services; cloud services store services; and operates various platforms, including the App Store, that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It sells and delivers third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1977 and is headquartered in Cupertino, California.',
    },
    '3' => {
      'name' => 'Walmart Inc.',
      'symbol' => 'WMT',
      'stock_desc' => 'Walmart Inc. engages in the retail and wholesale operations in various formats worldwide. The company operates in three segments: Walmart U.S., Walmart International, and Sam\'s Club. It operates supercenters, supermarkets, hypermarkets, warehouse clubs, cash and carry stores, discount stores, drugstores, and convenience stores; membership-only warehouse clubs; ecommerce websites, such as walmart.com, walmart.com.mx, asda.com, walmart.ca, flipkart.com, and samsclub.com; and mobile commerce applications. The company offers grocery products, including meat, produce, natural and organics, deli and bakery, dairy, frozen foods, alcoholic and nonalcoholic beverages, and floral and dry grocery, as well as consumables, such as health and beauty aids, baby products, household chemicals, paper goods, and pet supplies; and health and wellness products. It also provides electronics, cameras and supplies, photo processing services, wireless, movies, music, video games, and books; stationery, automotive, hardware and paint, sporting goods, and outdoor living and horticulture; apparel for women, girls, men, boys, and infants, as well as shoes, jewelry, and accessories; and home furnishings, housewares and small appliances, bedding, home decor, toys, fabrics, crafts, and seasonal merchandise, as well as brand name merchandise. In addition, the company offers fuel and financial services and related products, including money orders, prepaid cards, money transfers, check cashing, and bill payment. It operates approximately 11,500 stores and various e-commerce Websites under the 56 banners in 27 countries. The company was formerly known as Wal-Mart Stores, Inc. and changed its name to Walmart Inc. in February 2018. Walmart Inc. was founded in 1945 and is based in Bentonville, Arkansas.',
    },
    '4' => {
      'name' => 'Berkshire Hathaway Inc.',
      'symbol' => 'BRK-B',
      'stock_desc' => 'Berkshire Hathaway Inc., through its subsidiaries, engages in insurance, freight rail transportation, and utility businesses. It provides property, casualty, life, accident, and health insurance and reinsurance; and operates railroad systems in North America. The company also generates, transmits, stores, and distributes electricity from natural gas, coal, wind, solar, hydro, nuclear, and geothermal sources; operates natural gas distribution and storage facilities, interstate pipelines, and compressor and meter stations; and holds interest in coal mining assets. In addition, it offers real estate brokerage services; and leases transportation equipment and furniture. Further, the company manufactures boxed chocolates and other confectionery products; specialty chemicals, metal cutting tools, and components for aerospace and power generation applications; flooring, insulation, roofing and engineered, building and engineered components, paints and coatings, and bricks and masonry products, as well as offers homebuilding and manufactured housing finance; and recreational vehicles, apparel products, jewelry, and custom picture framing products, and alkaline batteries. Additionally, it manufactures castings, forgings, fasteners/fastener systems, and aerostructures; and seamless pipes, fittings, downhole casing and tubing, and various mill forms. The company distributes newspapers, televisions, and information; franchises and services quick service restaurants; distributes electronic components; and offers logistics services, grocery and foodservice distribution services, and professional aviation training and fractional aircraft ownership programs. It also retails automobiles; furniture, bedding, and accessories; household appliances, electronics, and computers; jewelry, watches, crystal, china, stemware, flatware, gifts, and collectibles; kitchenware; and motorcycle accessories. The company was incorporated in 1998 and is headquartered in Omaha, Nebraska.',
    },
    '5' => {
      'name' => 'Facebook, Inc.',
      'symbol' => 'FB',
      'stock_desc' => 'Facebook, Inc. develops products that enable people to connect and share with friends and family through mobile devices, personal computers, virtual reality headsets, and in-home devices worldwide. The company\'s products include Facebook that enables people to connect, share, discover, and communicate with each other on mobile devices and personal computers; Instagram, a community for sharing photos, videos, and private messages; Messenger, a messaging application for people to connect with friends, family, groups, and businesses across platforms and devices; and WhatsApp, a messaging application that is used by people and businesses to communicate in a private way. It also provides Oculus, a hardware, software, and developer ecosystem, which allows people to come together and connect with each other through its Oculus virtual reality products. Facebook, Inc. was founded in 2004 and is headquartered in Menlo Park, California.',
    },
    '6' => {
      'name' => 'Tesla, Inc.',
      'symbol' => 'TSLA',
      'stock_desc' => 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, Netherlands, Norway, and internationally. The company operates in two segments, Automotive; and Energy Generation and Storage. The Automotive segment offers sedans and sport utility vehicles. It also provides electric powertrain components and systems; and services for electric vehicles through its company-owned service locations, and Tesla mobile service technicians, as well as sells used vehicles. This segment markets and sells its products through a network of company-owned stores and galleries, as well as through its own Website. The Energy Generation and Storage segment offers energy storage products, such as rechargeable lithium-ion battery systems for use in homes, industrial, commercial facilities, and utility grids; and designs, manufactures, installs, maintains, leases, and sells solar energy generation and energy storage products to residential and commercial customers. It also provides vehicle insurance services, as well as renewable energy. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was founded in 2003 and is headquartered in Palo Alto, California.',
    },
    '7' => {
      'name' => 'Snowflake Inc.',
      'symbol' => 'SNOW',
      'stock_desc' => 'Snowflake Inc. provides cloud-based data platform in the United States and internationally. The company\'s platform enables customers to consolidate data into a single source of truth to drive meaningful business insights, build data-driven applications, and share data. Its platform is used by various organizations of various sizes in a range of industries. The company was formerly known as Snowflake Computing, Inc. and changed its name to Snowflake Inc. in April 2019. Snowflake Inc. was founded in 2012 and is headquartered in San Mateo, California.',
    },
    '8' => {
      'name' => 'Barrick Gold',
      'symbol' => 'GOLD',
      'stock_desc' => 'Barrick Gold Corporation engages in the exploration, mine development, production, and sale of gold and copper properties. It has ownership interests in producing gold mines that are located in Argentina, Canada, CÃ´te d\'Ivoire, the Democratic Republic of Congo, the Dominican Republic, Mali, Papua New Guinea, Tanzania, and the United States. The company also has ownership interests in producing copper mines located in Chile, Saudi Arabia, and Zambia; and various other projects located throughout the Americas. Barrick Gold Corporation was founded in 1983 and is headquartered in Toronto, Canada.',
    },
    '9' => {
      'name' => 'Microsoft Corporation',
      'symbol' => 'MSFT',
      'stock_desc' => 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); Skype, Outlook.com, and OneDrive; LinkedIn that includes Talent, Learning, Sales, and Marketing solutions, as well as premium subscriptions; and Dynamics 365, a set of cloud-based and on-premises business solutions for small and medium businesses, large organizations, and divisions of enterprises. Its Intelligent Cloud segment licenses SQL and Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also offers support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification to developers and IT professionals on various Microsoft products. Its More Personal Computing segment provides Windows original equipment manufacturer (OEM) licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also offers Surface, PC accessories, PCs, tablets, gaming and entertainment consoles, and other intelligent devices; Gaming, including Xbox hardware, and Xbox content and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online stores, and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.',
    },
    '10' => {
      'name' => 'Caterpillar Inc.',
      'symbol' => 'CAT',
      'stock_desc' => 'Caterpillar Inc. manufactures and sells construction and mining equipment, diesel and natural gas engines, and industrial gas turbines. Its Construction Industries segment offers asphalt pavers, compactors, cold planers, feller bunchers, harvesters, motorgraders, pipelayers, road reclaimers, skidders, telehandlers, and utility vehicles; backhoe, knuckleboom, compact track, multi-terrain, skid steer, and track-type loaders; forestry and wheel excavators; and site prep and track-type tractors. The company\'s Resource Industries segment provides electric rope and hydraulic shovels, draglines, rotary drills, hard rock vehicles, track-type tractors, mining trucks, longwall miners, wheel loaders, off-highway and articulated trucks, wheel tractor scrapers, wheel dozers, landfill and soil compactors, machinery components, autonomous vehicles and solutions, select work tools, and hard rock continuous mining systems. Its Energy & Transportation segment offers reciprocating engine powered generator sets; reciprocating engines and integrated systems for the power generation, marine, oil, and gas industries; turbines, centrifugal gas compressors, and related services; remanufactured reciprocating engines and components; and diesel-electric locomotives and components, and other rail-related products. The company\'s Financial Products segment provides operating and finance leases, installment sale contracts, working capital loans, and wholesale financing; and insurance and risk management. Its All Other operating segment manufactures filters and fluids, undercarriage, ground engaging tools, fluid transfer products, precision seals, and rubber sealing and connecting components; parts distribution; integrated logistics solutions and distribution services; and digital investments services. The company was formerly known as Caterpillar Tractor Co. and changed its name to Caterpillar Inc. in 1986. The company was founded in 1925 and is headquartered in Deerfield, Illinois.',
    },
    '11' => {
      'name' => '3M Company',
      'symbol' => 'MMM',
      'stock_desc' => '3M Company develops, manufactures, and markets various products worldwide. It operates through four business segments: Safety and Industrial, Transportation and Electronics, Health Care, and Consumer. The Safety and Industrial segment offers personal safety products, industrial adhesives and tapes, abrasives, closure and masking systems, electrical markets, automotive aftermarket, and roofing granules to industrial, electrical, and safety markets. The Transportation and Electronics provides electronics, such as display materials and systems, electronic materials solutions; automotive and aerospace, and commercial solutions; advanced materials; and transportation safety products to transportation and electronic original equipment manufacturer customers. The Health Care segment offers medical and surgical supplies, skin health and infection prevention products, oral care, separation and purification sciences, health information systems, drug delivery systems, and food safety products to healthcare industry. The Consumer segment provides home improvement, home care, and consumer health care products, as well as stationery and office supplies to various consumers. This segment is also involved in the retail auto care business. It offers its products through various e-commerce and traditional wholesalers, retailers, jobbers, distributors, and dealers, as well as directly to users. 3M Company has a strategic collaboration with Merry Maids in residential cleaning sector. The company was founded in 1902 and is headquartered in St. Paul, Minnesota.',
    },
    '12' => {
      'name' => 'American Express Company',
      'symbol' => 'AXP',
      'stock_desc' => 'American Express Company, together with its subsidiaries, provides charge and credit payment card products, and travel-related services worldwide. The company operates through three segments: Global Consumer Services Group, Global Commercial Services, and Global Merchant and Network Services. Its products and services include payment and financing products; network services; expense management products and services; and lifestyle services. The company\'s products and services also comprise merchant acquisition and processing, servicing and settlement, point-of-sale marketing, and information products and services for merchants; and fraud prevention services, as well as the design and operation of customer loyalty programs. It sells its products and services to consumers, small businesses, mid-sized companies, and large corporations through mobile and online applications, third-party vendors and business partners, direct mail, telephone, in-house sales teams, and direct response advertising. American Express Company was founded in 1850 and is headquartered in New York, New York.',
    },
    '13' => {
      'name' => 'The Boeing Company',
      'symbol' => 'BA',
      'stock_desc' => 'The Boeing Company, together with its subsidiaries, designs, develops, manufactures, sales, services, and supports commercial jetliners, military aircraft, satellites, missile defense, human space flight and launch systems, and services worldwide. The company operates through four segments: Commercial Airplanes; Defense, Space & Security; Global Services; and Boeing Capital. The Commercial Airplanes segment develops, produces, and markets commercial jet aircraft and provides fleet support services principally to the commercial airline industry. The Defense, Space & Security segment engages in the research, development, production, and modification of manned and unmanned military aircraft and weapons systems for strike, surveillance, and mobility, including fighter and trainer aircraft; vertical lift comprising rotorcraft and tilt-rotor aircraft; commercial derivative aircraft, such as anti-submarine and tanker aircraft; strategic defense and intelligence systems consisting of strategic missile and defense systems, cyber and information solutions, and intelligence systems, as well as command, control, communications, computers, intelligence, surveillance, and reconnaissance products; satellite systems, including government and commercial satellites, and space exploration. The Global Services segment offers various products and services comprising supply chain and logistics management, engineering, maintenance and modifications, upgrades and conversions, spare parts, pilot and maintenance training systems and services, technical and maintenance documents, and data analytics and digital services to commercial and defense customers. The Boeing Capital segment offers financing services and manages financing exposure for a portfolio of equipment under operating and finance leases, notes and other receivables, assets held for sale or re-lease, and investments. The Boeing Company was founded in 1916 and is based in Chicago, Illinois.',
    },
    '14' => {
      'name' => 'Cisco Systems Inc.',
      'symbol' => 'CSCO',
      'stock_desc' => 'Cisco Systems, Inc. designs, manufactures, and sells Internet Protocol based networking and other products related to the communications and information technology industry in the Americas, Europe, the Middle East, Africa, the Asia Pacific, Japan, and China. It provides infrastructure platforms, including networking technologies of switching, routing, wireless, and data center products that are designed to work together to deliver networking capabilities, and transport and/or store data. The company also offers collaboration products comprising unified communications, Cisco TelePresence, and conferencing, as well as the Internet of Things and analytics software. In addition, it provides security products, such as network security, cloud and email security, identity and access management, advanced threat protection, and unified threat management products; and cloud and system management products. Further, the company offers a range of service and support options for its customers, including technical support and advanced services. It serves businesses of various sizes, public institutions, governments, and service providers. The company sells its products and services directly, as well as through systems integrators, service providers, other resellers, and distributors. Cisco Systems, Inc. has a strategic alliance with Internet2 to deliver next-generation capabilities and software solutions. Cisco Systems, Inc. was founded in 1984 and is headquartered in San Jose, California.',
    },
    '15' => {
      'name' => 'The Coca Cola Company',
      'symbol' => 'KO',
      'stock_desc' => 'The Coca-Cola Company, a beverage company, manufactures, markets, and sells various nonalcoholic beverages worldwide. The company provides sparkling soft drinks; water, enhanced water, and sports drinks; juice, dairy, and plantÂbased beverages; tea and coffee; and energy drinks. It also offers beverage concentrates and syrups, as well as fountain syrups to fountain retailers, such as restaurants and convenience stores. The company sells its products under the Coca-Cola, Diet Coke/Coca-Cola Light, Coca-Cola Zero Sugar, Fanta, Fresca, Schweppes, Sprite, Thums Up, Aquarius, Ciel, Dasani, glacÃ©au smartwater, glacÃ©au vitaminwater, Ice Dew, I LOHAS, Powerade, Topo Chico, AdeS, Del Valle, fairlife, innocent, Minute Maid, Minute Maid Pulpy, Simply, ZICO, Ayataka, Costa, dogadan, FUZE TEA, Georgia, Gold Peak, HONEST TEA, and Kochakaden brands. It operates through a network of company-owned or controlled bottling and distribution operators, as well as through independent bottling partners, distributors, wholesalers, and retailers. The company was founded in 1886 and is headquartered in Atlanta, Georgia.',
    },
    '16' => {
      'name' => 'The Goldman Sachs Group, Inc.',
      'symbol' => 'GS',
      'stock_desc' => 'The Goldman Sachs Group, Inc. operates as an investment banking, securities, and investment management company worldwide. It operates in four segments: Investment Banking, Global Markets, Asset Management, and Consumer & Wealth Management. The company\'s Investment Banking segment provides financial advisory services, including strategic advisory assignments related to mergers and acquisitions, divestitures, corporate defense activities, restructurings, and spin-offs; and middle-market lending, relationship lending, and acquisition financing, as well as transaction banking services. This segment also offers underwriting services, such as equity underwriting for common and preferred stock and convertible and exchangeable securities; and debt underwriting for various types of debt instruments, including investment-grade and high-yield debt, bank and bridge loans, and emerging- and growth-market debt. Its Global Markets segment is involved in client execution activities for cash and derivative instruments; credit products; mortgages; currencies; commodities; and equities; and provision of equity intermediation, and equity financing services, as well as offers clearing, settlement and custody services. The company\'s Asset Management segment manages assets across various asset classes, including equity, fixed income, hedge funds, credit funds, private equity, real estate, currencies, and commodities; and provides customized investment advisory solutions, and financing services, as well as invests in corporate, real estate, and infrastructure entities. Its Consumer & Wealth Management segment offers wealth advisory and banking services, including financial planning, investment management, and lending; private banking and lending services; unsecured loans; and saving and time deposits. The company serves corporations, financial institutions, governments, and individuals. The Goldman Sachs Group, Inc. was founded in 1869 and is headquartered in New York, New York.',
    },
    '17' => {
      'name' => 'Honeywell International Inc.',
      'symbol' => 'HON',
      'stock_desc' => 'Honeywell International Inc. operates as a diversified technology and manufacturing company worldwide. The Aerospace segment offers auxiliary power units, propulsion engines, integrated avionics, environmental control and electric power systems, engine controls, flight safety, communications, navigation hardware, data and software applications, radar and surveillance systems, aircraft lighting, advanced systems and instruments, satellite and space components, and aircraft wheels and brakes; spare parts; repair, overhaul, and maintenance services; thermal systems; and connected solutions and data services for the aftermarket, as well as wireless connectivity, and management and technical services. The company\'s Honeywell Building Technologies segment offers advanced software applications for building control and optimization; sensors, switches, control systems and instruments for energy management; access control; video surveillance; fire products; remote patient monitoring systems; e-cooling heat transfer agents; and installation, maintenance, and upgrades of systems. Its Performance Materials and Technologies segment offers automation control, instrumentation, and advanced software and related services; catalysts and adsorbents, equipment, and consulting; and materials used to manufacture end products, such as bullet-resistant armor, nylon, computer chips, and pharmaceutical packaging, as well as Honeywell forge connected solutions. The company\'s Safety and Productivity Solutions segment provides personal protection equipment, apparel, gear, and footwear; gas detection technology; and cloud-based notification and emergency messaging; and mobile devices and software; supply chain and warehouse automation equipment, and software and solutions; custom-engineered sensors, switches, and controls; and software-based data and asset management productivity solutions. Honeywell International Inc. was incorporated in 1985 and is headquartered in Charlotte, North Carolina.',
    },
    '18' => {
      'name' => 'Int. Business Machines Corp.',
      'symbol' => 'IBM',
      'stock_desc' => 'International Business Machines Corporation operates as an integrated solutions and services company worldwide. Its Cloud & Cognitive Software segment offers software for vertical and domain-specific solutions in health, financial services, and Internet of Things (IoT), weather, and security software and services application areas; and customer information control system and storage, and analytics and integration software solutions to support client mission critical on-premise workloads in banking, airline, and retail industries. It also offers middleware and data platform software, including Red Hat, which enables the operation of clients\' hybrid multi-cloud environments; and Cloud Paks, WebSphere distributed, and analytics platform software, such as DB2 distributed, information integration, and enterprise content management, as well as IoT, Blockchain and AI/Watson platforms. The company\'s Global Business Services segment offers business consulting services; system integration, application management, maintenance, and support services for packaged software; finance, procurement, talent and engagement, industry-specific business process outsourcing services; IT infrastructure and platform services. Its Global Technology Services segment provides project, managed, outsourcing, and cloud-delivered services for enterprise IT infrastructure environments; and IT infrastructure support services. It\'s Systems segment offers servers for businesses, cloud service providers, and scientific computing organizations; data storage products and solutions; and z/OS, an enterprise operating system, as well as Linux. Its Global Financing segment provides lease, installment payment, loan financing, short-term working capital financing, and remanufacturing and remarketing services. It was formerly known as Computing-Tabulating-Recording Co. and changed its name to International Business Machines Corporation in 1924. It was founded in 1911 and is headquartered in Armonk, New York.',
    },
    '19' => {
      'name' => 'Intel Corporation',
      'symbol' => 'INTC',
      'stock_desc' => 'Intel Corporation designs, manufactures, and sells essential technologies for the cloud, smart, and connected devices worldwide. The company operates through DCG, IOTG, Mobileye, NSG, PSG, CCG, and All Other segments. It offers platform products, such as central processing units and chipsets, and system-on-chip and multichip packages; and non-platform or adjacent products comprising accelerators, boards and systems, connectivity products, and memory and storage products. The company also provides Internet of things products, including high-performance compute solutions for targeted verticals and embedded applications; and computer vision and machine learning-based sensing, data analysis, localization, mapping, and driving policy technology. It serves original equipment manufacturers, original design manufacturers, and cloud service providers. The company has collaborations with UC San Francisco\'s Center for Digital Health Innovation, Fortanix, and Microsoft Azure to establish a computing platform with privacy-preserving analytics to accelerate the development and validation of clinical algorithms. Intel Corporation was founded in 1968 and is headquartered in Santa Clara, California.',
    },
    '20' => {
      'name' => 'The Walt Disney Company',
      'symbol' => 'DIS',
      'stock_desc' => 'The Walt Disney Company, together with its subsidiaries, operates as an entertainment company worldwide. The company\'s Media Networks segment operates domestic cable networks under the Disney, ESPN, Freeform, FX, and National Geographic brands; and television broadcast network under the ABC brand, as well as eight owned domestic television stations. This segment is also involved in the television production and distribution; and operation of National Geographic magazines. Its Parks, Experiences and Products segment operates theme parks and resorts, such as Walt Disney World Resort in Florida; Disneyland Resort in California; Disneyland Paris; Hong Kong Disneyland Resort; and Shanghai Disney Resort; Disney Cruise Line, Disney Vacation Club, National Geographic Expeditions, and Adventures by Disney; and Aulani, a Disney resort and spa in Hawaii, as well as licenses its intellectual property to a third party for the operations of the Tokyo Disney Resort in Japan. The company\'s Studio Entertainment segment produces and distributes motion pictures under the Walt Disney Pictures, Twentieth Century Fox, Marvel, Lucasfilm, Pixar, Fox Searchlight Pictures, and Blue Sky Studios banners; develops, produces, and licenses live entertainment events; produces and distributes music; and provides post-production services, including visual and audio effects. Its Direct-To-Consumer & International segment operates international television networks and channels comprising Disney, ESPN, Fox, National Geographic, Star, and Other India Channels; direct-to-consumer streaming services consisting of Disney +, ESPN+, Hotstar, and Hulu; and operates branded apps and Websites, such as Disney Movie Club and Disney Digital Network, as well as provides streaming technology support services. The company was founded in 1923 and is based in Burbank, California.',
    },
    '21' => {
      'name' => 'Visa Inc.',
      'symbol' => 'V',
      'stock_desc' => 'Visa Inc. operates as a payments technology company worldwide. The company facilitates commerce through the transfer of value and information among consumers, merchants, financial institutions, businesses, strategic partners, and government entities. It operates VisaNet, a processing network that enables authorization, clearing, and settlement of payment transactions. In addition, the company offers card products, as well as value-added services. It provides its services under the Visa, Visa Electron, Interlink, V PAY, and PLUS brands. Visa Inc. has a strategic partnership with NovoPayment to enable financial institutions and merchants to deploy Visa\'s digital solutions in Latin America and the Caribbean; and a strategic agreement with Intuit Inc. The company was founded in 1958 and is headquartered in San Francisco, California.',
    },
    '22' => {
      'name' => 'Verizon Communications Inc.',
      'symbol' => 'VZ',
      'stock_desc' => 'Verizon Communications Inc. offers communications, information, and entertainment products and services to consumers, businesses, and governmental entities worldwide. Its Consumer segment provides postpaid and prepaid service plans; Internet access on notebook computers and tablets; wireless equipment, including smartphones and other handsets; and wireless-enabled Internet devices, such as tablets, laptop computers and netbooks, and other wireless-enabled connected devices, such as smart watches and other wearables. It also provides residential fixed connectivity solutions, including Internet, video, and voice services; and sells network access to mobile virtual network operators. As of December 31, 2019, it had approximately 95 million wireless retail connections, 6 million broadband connections, and 4 million Fios video connections. The company\'s Business segment provides network connectivity products, including private networking, private cloud connectivity, virtual and software defined networking, and Internet access services; and Internet protocol-based voice services, unified communications and collaboration tools, and customer contact center solutions. It also offers a suite of management and data security services; domestic and global voice and data solutions, including voice calling, messaging services, conferencing, contact center solutions, and private line and data access networks; customer premises equipment; installation, maintenance, and site services; and IoT products and services. This segment had 25 million wireless retail postpaid connections and 489 thousand broadband connections. The company has strategic partnership with HERE Technologies and Dignitas; and Emory Healthcare to develop and test 5G Ultra Wideband-enabled use cases. The company was formerly known as Bell Atlantic Corporation and changed its name to Verizon Communications Inc. in June 2000. Verizon Communications Inc. was founded in 1983 and is headquartered in New York, New York.',
    },
    '23' => {
      'name' => 'JPMorgan Chase & Co.',
      'symbol' => 'JPM',
      'stock_desc' => 'JPMorgan Chase & Co. operates as a financial services company worldwide. It operates in four segments: Consumer & Community Banking (CCB), Corporate & Investment Bank (CIB), Commercial Banking (CB), and Asset & Wealth Management (AWM). The CCB segment offers deposit and investment products and services to consumers; lending, deposit, and cash management and payment solutions to small businesses; mortgage origination and servicing activities; residential mortgages and home equity loans; and credit card, payment processing, auto loan, and leasing services. The CIB segment provides investment banking products and services, including corporate strategy and structure advisory, and equity and debt markets capital-raising services, as well as loan origination and syndication; cash management and liquidity solutions; and cash securities and derivative instruments, risk management solutions, prime brokerage, and research. This segment also offers securities services, including custody, fund accounting and administration, and securities lending products for asset managers, insurance companies, and public and private investment funds. The CB segment provides financial solutions, including lending, treasury, investment banking, and asset management to small business, large and midsized corporations, local governments, and nonprofit clients; and commercial real estate banking services to investors, developers, and owners of multifamily, as well as to office, retail, industrial, and affordable housing properties. The AWM segment offers investment and wealth management services across equities, fixed income, alternatives, and money market fund asset classes; multi-asset investment management services; retirement products and services; and brokerage and banking services. The company also provides ATM, online and mobile, and telephone banking services. The company was founded in 1799 and is headquartered in New York, New York.',
    },
    '24' => {
      'name' => 'Johnson & Johnson',
      'symbol' => 'JNJ',
      'stock_desc' => 'Johnson & Johnson researches and develops, manufactures, and sells various products in the health care field worldwide. It operates in three segments: Consumer, Pharmaceutical, and Medical Devices. The Consumer segment offers baby care products under the JOHNSON\'S brand; oral care products under the LISTERINE brand; beauty products under the AVEENO, CLEAN & CLEAR, DR. CI:LABO NEUTROGENA, and OGX brands; over-the-counter medicines, including acetaminophen products under the TYLENOL brand; cold, flu, and allergy products under the SUDAFED brand; allergy products under the BENADRYL and ZYRTEC brands; ibuprofen products under the MOTRIN IB brand; and acid reflux products under the PEPCID brand. This segment also provides women\'s health products, such as sanitary pads and tampons under the STAYFREE, CAREFREE, and o.b. brands; wound care products comprising adhesive bandages under the BAND-AID brand; and first aid products under the NEOSPORIN brand. The Pharmaceutical segment offers products in various therapeutic areas, including immunology, infectious diseases, neuroscience, oncology, pulmonary hypertension, and cardiovascular and metabolic diseases. The Medical Devices segment provides orthopedic products; general surgery, biosurgical, endomechanical, and energy products; electrophysiology products to treat cardiovascular diseases; and vision care products, such as disposable contact lenses and ophthalmic products related to cataract and laser refractive surgery. The company markets its products to general public, and retail outlets and distributors, as well as distributes directly to wholesalers, hospitals, and health care professionals for prescription use. Johnson & Johnson was founded in 1886 and is based in New Brunswick, New Jersey.',
    },
    '25' => {
      'name' => 'NIKE, Inc.',
      'symbol' => 'NKE',
      'stock_desc' => 'NIKE, Inc., together with its subsidiaries, designs, develops, markets, and sells athletic footwear, apparel, equipment, and accessories worldwide. The company offers NIKE brand products in six categories, including running, NIKE basketball, the Jordan brand, football, training, and sportswear. It also markets products designed for kids, as well as for other athletic and recreational uses, such as American football, baseball, cricket, golf, lacrosse, skateboarding, tennis, volleyball, walking, wrestling, and other outdoor activities; and apparel with licensed college and professional team and league logos, as well as sells sports apparel. In addition, the company sells a line of performance equipment and accessories comprising bags, socks, sport balls, eyewear, timepieces, digital devices, bats, gloves, protective equipment, and other equipment for sports activities; and various plastic products to other manufacturers. Further, it provides athletic and casual footwear, apparel, and accessories under the Jumpman trademark; casual sneakers, apparel, and accessories under the Converse, Chuck Taylor, All Star, One Star, Star Chevron, and Jack Purcell trademarks; and action sports and youth lifestyle apparel and accessories under the Hurley trademark. Additionally, the company licenses agreements that permit unaffiliated parties to manufacture and sell apparel, digital devices, and applications and other equipment for sports activities under NIKE-owned trademarks. It sells its products to footwear stores; sporting goods stores; athletic specialty stores; department stores; skate, tennis, and golf shops; and other retail accounts through NIKE-owned retail stores, digital platforms, independent distributors, licensees, and sales representatives. The company was formerly known as Blue Ribbon Sports, Inc. and changed its name to NIKE, Inc. in 1971. NIKE, Inc. was founded in 1964 and is headquartered in Beaverton, Oregon.',
    },
    '26' => {
      'name' => 'The Procter & Gamble Company',
      'symbol' => 'PG',
      'stock_desc' => 'The Procter & Gamble Company provides branded consumer packaged goods to consumers in North and Latin America, Europe, the Asia Pacific, Greater China, India, the Middle East, and Africa. It operates in five segments: Beauty; Grooming; Health Care; Fabric & Home Care; and Baby, Feminine & Family Care. The Beauty segment offers conditioners, shampoos, styling aids, and treatments; and antiperspirants and deodorants, personal cleansing, and skin care products under the Head & Shoulders, Herbal Essences, Pantene, Rejoice, Olay, Old Spice, Safeguard, SK-II, and Secret brands. The Grooming segment provides female and male blades and razors, pre- and post-shave products, and other shave care products; and appliances that include electric shavers and epilators under the Braun, Gillette, and Venus brands. The Health Care segment offers toothbrushes, toothpaste, and other oral care products; and gastrointestinal, rapid diagnostics, respiratory, vitamins/minerals/supplements, pain relief, and other personal health care products under the Crest, Oral-B, Metamucil, Neurobion, Pepto Bismol, and Vicks brands. The Fabric & Home Care segment provides fabric enhancers, laundry additives, and laundry detergents; and air care, dish care, P&G professional, and surface care products under the Ariel, Downy, Gain, Tide, Cascade, Dawn, Fairy, Febreze, Mr. Clean, and Swiffer brands. The Baby, Feminine & Family Care segment baby wipes, taped diapers, and pants; adult incontinence and feminine care products; and paper towels, tissues, and toilet papers under the Luvs, Pampers Always, Always Discreet, Tampax Bounty, Charmin, and Puffs brands. The company sells its products through mass merchandisers, e-commerce, grocery stores, membership club stores, drug stores, department stores, distributors, wholesalers, baby stores, specialty beauty stores, high-frequency stores, pharmacies, electronics stores, and professional channels. The Procter & Gamble Company was founded in 1837 and is headquartered in Cincinnati, Ohio.',
    },
    '27' => {
      'name' => 'Alphabet Inc.',
      'symbol' => 'GOOG',
      'stock_desc' => 'Alphabet Inc. provides online advertising services in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It offers performance and brand advertising services. The company operates through Google and Other Bets segments. The Google segment offers products, such as Ads, Android, Chrome, Google Cloud, Google Maps, Google Play, Hardware, Search, and YouTube, as well as technical infrastructure. It also offers digital content, cloud services, hardware devices, and other miscellaneous products and services. The Other Bets segment includes businesses, including Access, Calico, CapitalG, GV, Verily, Waymo, and X, as well as Internet and television services. The company has an agreement with Sabre Corporation to develop an artificial intelligence-driven technology platform for travel. Alphabet Inc. was founded in 1998 and is headquartered in Mountain View, California.',
    },
    '28' => {
      'name' => 'salesforce.com, Inc.',
      'symbol' => 'CRM',
      'stock_desc' => 'salesforce.com, inc. develops enterprise cloud computing solutions with a focus on customer relationship management worldwide. The company offers Sales Cloud to store data, monitor leads and progress, forecast opportunities, and gain insights through analytics and relationship intelligence, as well as deliver quotes, contracts, and invoices. It also provides Service Cloud, which enables companies to deliver personalized customer service and support, as well as a field service solution that enables companies to connect agents, dispatchers, and mobile employees through a centralized platform, which helps to schedule and dispatch work, and track and manage jobs in real-time. In addition, the company offers Marketing Cloud to plan, personalize, and optimize one-to-one customer marketing interactions; and Commerce Cloud, which enables companies to enhance engagement, conversion, revenue, and loyalty from their customers. Further, it provides Customer 360 Platform that offers no-code to pro-code Platform-as-a-Service tools for building, securing, integrating, and managing the business apps; MuleSoft Anypoint Platform enables customers to connect any system, application, data, or device; Quip collaboration platform, which combines documents, spreadsheets, apps, and chat with live CRM data; and Tableau and Einstein Analytics, provides analytical technology to customers. Additionally, the company offers various solutions for financial services, healthcare and life sciences, manufacturing, consumer goods, government, and philanthropy. The company also provides professional services and education services, including instructor-led and online courses; and support and adoption programs. It provides its services through direct sales; and consulting firms, systems integrators, and other partners. Salesforce and Siemens has a strategic partnership. The company was founded in 1999 and is headquartered in San Francisco, California.',
    },
    '29' => {
      'name' => 'Chevron Corporation',
      'symbol' => 'CVX',
      'stock_desc' => 'Chevron Corporation, through its subsidiaries, engages in integrated energy, chemicals, and petroleum operations worldwide. The company operates in two segments, Upstream and Downstream. The Upstream segment is involved in the exploration, development, and production of crude oil and natural gas; processing, liquefaction, transportation, and regasification associated with liquefied natural gas; transportation of crude oil through pipelines; and transportation, storage, and marketing of natural gas, as well as operates a gas-to-liquids plant. The Downstream segment engages in refining crude oil into petroleum products; marketing crude oil and refined products; transporting crude oil and refined products through pipeline, marine vessel, motor equipment, and rail car; and manufacturing and marketing commodity petrochemicals, and fuel and lubricant additives, as well as plastics for industrial uses. Chevron Corporation is also involved in the cash management and debt financing activities; insurance operations; real estate activities; and technology businesses. The company was formerly known as ChevronTexaco Corporation and changed its name to Chevron Corporation in 2005. Chevron Corporation was founded in 1879 and is headquartered in San Ramon, California.',
    },
    '30' => {
      'name' => 'Accenture plc',
      'symbol' => 'ACN',
      'stock_desc' => 'Accenture plc, a professional services company, provides strategy and consulting, interactive, and technology and operations services worldwide. The company also provides outsourcing services. It serves communications, media, high tech, software, and platform companies; banking, capital market, and insurance industries; and consumer goods, retail, travel services, industrial, and life science industries, as well as clients in health, public service, chemicals and natural resources, energy, and utilities sectors. Accenture plc has alliance relationships with Adobe, Alibaba, Amazon Web Services, Blue Yonder, Cisco, Dell, Google, HPE, IBM RedHat, Microsoft, Oracle, Pegasystems, Salesforce, SAP, ServiceNow, VMWare, Workday, and Massachusetts Institute of Technology. The company was incorporated in 2009 and is based in Dublin, Ireland.',
    },

  }

  stock = stock.map do |num, info|
    info['image_url'] = "assets/logos/#{num}.svg"
    info
  end

  Stock.create!(stock)
  
end
